
// This file was generated by Intellego. Do not modify

class RealHandCodedLightSeeker
{
	public static void main(String args[])
	{
		HandCodedLightSeeker a=new HandCodedLightSeeker();
		a.initController(new real.RealRCX(a));
		a.run();
	}
}